" vimrc
" -----

" VIM and NeoVim configuration.
set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after

set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after

let g:netrw_home = $XDG_DATA_HOME . '/vim'
if isdirectory($XDG_DATA_HOME)
    set viewdir=$XDG_DATA_HOME/vim/view
else
    set viewdir=$HOME/.vim/view
endif
call mkdir(&viewdir, 'p')

if isdirectory($XDG_CACHE_HOME)
    set backupdir=$XDG_CACHE_HOME/vim/backup
    set directory=$XDG_CACHE_HOME/vim/swap
    set undodir=$XDG_CACHE_HOME/vim/undo
    if !has('nvim') | set viminfofile=$XDG_CACHE_HOME/vim/viminfo | endif
else
    set backupdir=$HOME/.vim/backup
    set directory=$HOME/.vim/swap
    set undodir=$HOME/.vim/undo
    if !has('nvim') | set viminfofile=$HOME/.vim/viminfo | endif
endif
call mkdir(&backupdir, 'p')
call mkdir(&directory, 'p')
call mkdir(&undodir, 'p')

set enc=utf-8
set fenc=utf-8
set termencoding=utf-8

" disable vi compat
set nocompatible

" allow local vimrc
set exrc
" disallow :autocmd, shell, and write commands in local rc
set secure

" indentation
set autoindent
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab

" show whitespace
set list
set listchars=tab:→\ ,trail:·,nbsp:␣
set fillchars=vert:╎,foldsep:╎,foldopen:•,foldclose:‣,eob:┊
" show foldcolumn only if necessary
if has('nvim') | set foldcolumn=auto | endif

" gutter
set colorcolumn=81,101
" line numbers
set number
" highlight cursor line
set cursorline
set cursorlineopt=number

" highlighting
syntax enable
" highlight braces
set showmatch
set comments=sl:/*,mb:\ *,elx:\ */

" detect filetype
filetype plugin indent on
" load file changes
set autoread
" how long to wait to update after finishing typing
set updatetime=2400

" mostly case-insensitive search
set smartcase
set ignorecase

" Disable F1.
imap <F1> <nop>
nmap <F1> <nop>
" use F1 as the leader
let mapleader=' '
noremap <Leader> <nop>

" tab to esc
noremap <Tab> <Esc>
vnoremap <Tab> <Esc>gV
onoremap <Tab> <Esc>
inoremap <Tab> <Esc>`^
" shift-tab outputs tab in insert mode
inoremap <S-Tab> <Tab>
" inoremap <Leader><Tab> <S-Tab>

" ; to :
map ; :
noremap <Leader>; ;

" use F7 to enter paste mode
set pastetoggle=<F7>

" " mouse compat
" set mouse=a
" always show at least one line above/below cursor
set scrolloff=1

" completion menu
set wildmenu
" show the statusline
set laststatus=2
" hide the mode
set noshowmode

" statusline
set statusline=
set statusline+=%#StatusLine#
set statusline+=\ %f\ 
set statusline+=%#Search#
set statusline+=\ %{strtrans(mode())}\ 
set statusline+=%#Normal#
set statusline+=%(\ %r%)%(\ %h%)%(\ %w%)%(\ %m%)%=
set statusline+=\ %y\ 
set statusline+=%#Search#
set statusline+=\ %3p%%\ 
set statusline+=%#StatusLine#
set statusline+=\ %3l:%-2v\ 

if filereadable($XDG_CONFIG_HOME . '/vim/plugins.vim')
    source $XDG_CONFIG_HOME/vim/plugins.vim
elseif filereadable($HOME . '/.vim/plugins.vim')
    source $HOME/.vim/plugins.vim
endif

