" vimrc
" -----

" VIM and NeoVim configuration.
set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after

set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after

let g:netrw_home = $XDG_DATA_HOME."/vim"
call mkdir($XDG_DATA_HOME."/vim/spell", 'p')
set viewdir=$XDG_DATA_HOME/vim/view | call mkdir(&viewdir, 'p')

set backupdir=$XDG_CACHE_HOME/vim/backup | call mkdir(&backupdir, 'p')
set directory=$XDG_CACHE_HOME/vim/swap   | call mkdir(&directory, 'p')
set undodir=$XDG_CACHE_HOME/vim/undo     | call mkdir(&undodir,   'p')

if !has('nvim') | set viminfofile=$XDG_CACHE_HOME/vim/viminfo | endif

set enc=utf-8
set fenc=utf-8
set termencoding=utf-8

" disable vi compat
set nocompatible

" allow local vimrc
set exrc

" indentation
set autoindent
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab

" show whitespace
set list
set listchars=tab:→\ ,trail:·,nbsp:␣

" gutter
set colorcolumn=81,101
" line numbers
set number

" highlighting
syntax enable
" highlight braces
set showmatch
set comments=sl:/*,mb:\ *,elx:\ */

" detect filetype
filetype plugin indent on

" mostly case-insensitive search
set smartcase
set ignorecase

let mapleader="\<F6>"

" tab to esc
noremap <Tab> <Esc>
vnoremap <Tab> <Esc>gV
onoremap <Tab> <Esc>
inoremap <Tab> <Esc>`^
" shift-tab outputs tab in insert mode
inoremap <Leader><Tab> <Tab>

" ; to :
map ; :
" ampersand in normal mode for custom macros
noremap & :A
vnoremap & :A
" map &sw to sudo write
" https://stackoverflow.com/a/7078429
command Asw w !sudo tee > /dev/null %

" use F7 to enter paste mode
set pastetoggle=<F7>

" show the statusline
set laststatus=2
" completion menu
set wildmenu
" " mouse compat
" set mouse=a

" 16-color color scheme
colorscheme catalina

source $XDG_CONFIG_HOME/vim/plugins.vim

