# .bash_profile
# -------------
# Symlink to ~/.bash_profile.
# If this file is not found, bash will look for .bash_login and then
# .profile, in that order.

source "$HOME/.profile"

if [[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/bash/local/profile.bash" ]] ; then
    source "${XDG_CONFIG_HOME:-$HOME/.config}/bash/local/profile.bash"
fi

add_local_bin_to_path

# vim: set ft=bash:
